#8 add simple maven cucumber example
sitture/cucumber-jvm-extentreport pull request #10
Opened 2017-10-16 21:52 UTC by joergsesterhenn

This is one of my first PRs so please let me know if anything needs to be changed 😉

2017-10-17 11:47 UTC, haroon-sheikh requested changes
Hi @joergsesterhenn, thanks a ton for your contribution. Just a few minor changes to make please.

2017-10-17 11:47 UTC, haroon-sheikh commented on examples/maven/pom.xml
> +	</dependencies>
Can we remove any dependencies that are not being used?

2017-10-17 11:47 UTC, haroon-sheikh commented on examples/maven/pom.xml
> +		<maven-javadoc-plugin.version>2.10.4</maven-javadoc-plugin.version>
Remove unused properties

2017-10-17 11:47 UTC, haroon-sheikh commented on examples/maven/pom.xml
> +      <version>2.0.3-SNAPSHOT</version>
lets move this version into properties?

2017-10-17 21:27 UTC, joergsesterhenn commented
I hope this is acceptable?

2017-10-19 19:40 UTC, haroon-sheikh approved these changes

2017-10-19 19:40 UTC, merged